### ISSUE TITLE
[FIX] Hypertable per le Logs

### ISSUE THREAD

**Issue by Maxelweb** [Maxelweb/swe-kafka-db#9]
L'hypertable per le logs non sembra essere giusta. Scritta in quel modo, non serve a niente, dal momento che le logs devono basarsi sui dati che sono visualizzati dai casi d'uso relativi.

> La tabella va cambiata il prima possibile e riscritta nel modo corretto :fire:

**Comment by lorenzodeinegri** [comment]
@Maxelweb 
Hai perfettamente ragione, quando l'ho scritta non avevo idea di cosa metterci dentro, quindi l'avevo lasciata vuota, non pensado per nulla che c'è il caso d'uso appostito.
